name: world_clock
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The correct package and version for your system
  solar_calculator: ^1.0.3

  # Other packages
  provider: ^6.1.2
  http: ^1.2.1
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  flutter_spinkit: ^5.2.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/